#!/usr/bin/python

daug_parent = {
 	'Cholesterol':'Sterols',
	'ERG':'Sterols',
	'DLPA':'PA',
	'DMPA':'PA',
	'DPPA':'PA',
	'DSPA':'PA',
	'POPA':'PA',
	'PLPA':'PA',
	'SOPA':'PA',
	'SLPA':'PA',
	'DYPA':'PA',
	'YOPA':'PA',
	'DOPA':'PA',
	'DGPA':'PA',
	'DEPA':'PA',
	'DNPA':'PA',
	'DDPC':'PC',
	'DCPC':'PC',
	'DLPC':'PC',
	'DMPC':'PC',
	'DPPC':'PC',
	'DSPC':'PC',
	'POPC':'PC',
	'PLPC':'PC',
	'SOPC':'PC',
	'SLPC':'PC',
	'DYPC':'PC',
	'YOPC':'PC',
	'DOPC':'PC',
	'DUPC':'PC',
	'DGPC':'PC',
	'DEPC':'PC',
	'DNPC':'PC',
	'DLPE':'PE',
	'DMPE':'PE',
	'DPPE':'PE',
	'DSPE':'PE',
	'PYPE':'PE',
	'POPE':'PE',
	'PLPE':'PE',
	'SOPE':'PE',
	'SLPE':'PE',
	'DYPE':'PE',
	'YOPE':'PE',
	'OYPE':'PE',
	'DOPE':'PE',
	'DGPE':'PE',
	'DEPE':'PE',
	'DNPE':'PE',
	'DLPG':'PG',
	'DMPG':'PG',
	'DPPG':'PG',
	'DSPG':'PG',
	'PYPG':'PG',
	'POPG':'PG',
	'PLPG':'PG',
	'SOPG':'PG',
	'SLPG':'PG',
	'DYPG':'PG',
	'DOPG':'PG',
	'DGPG':'PG',
	'DEPG':'PG',
	'DNPG':'PG',
	'DLPS':'PS',
	'DMPS':'PS',
	'DPPS':'PS',
	'DSPS':'PS',
	'POPS':'PS',
	'PLPS':'PS',
	'SOPS':'PS',
	'SLPS':'PS',
	'DYPS':'PS',
	'YOPS':'PS',
	'DOPS':'PS',
	'DGPS':'PS',
	'DEPS':'PS',
	'DNPS':'PS',
	'DMPI':'PI',
	'DMPI13':'PI',
	'DMPI14':'PI',
	'DMPI15':'PI',
	'DMPI24':'PI',
	'DMPI25':'PI',
	'DMPI2A':'PI',
	'DMPI2B':'PI',
	'DMPI2C':'PI',
	'DMPI2D':'PI',
	'DMPI33':'PI',
	'DMPI34':'PI',
	'DMPI35':'PI',
	'PYPI':'PI',
	'POPI':'PI',
	'POPI13':'PI',
	'POPI14':'PI',
	'POPI15':'PI',
	'POPI24':'PI',
	'POPI25':'PI',
	'POPI2A':'PI',
	'POPI2B':'PI',
	'POPI2C':'PI',
	'POPI2D':'PI',
	'POPI33':'PI',
	'POPI34':'PI',
	'POPI35':'PI',
	'PLPI':'PI',
	'PLPI13':'PI',
	'PLPI14':'PI',
	'PLPI15':'PI',
	'PLPI24':'PI',
	'PLPI25':'PI',
	'PLPI2A':'PI',
	'PLPI2B':'PI',
	'PLPI2C':'PI',
	'PLPI2D':'PI',
	'PLPI33':'PI',
	'PLPI34':'PI',
	'PLPI35':'PI',
	'PNPI':'PI',
	'PNPI13':'PI',
	'PNPI14':'PI',
	'PNPI15':'PI',
	'PNPI24':'PI',
	'PNPI25':'PI',
	'PNPI2A':'PI',
	'PNPI2B':'PI',
	'PNPI2C':'PI',
	'PNPI2D':'PI',
	'PNPI33':'PI',
	'PNPI34':'PI',
	'PNPI35':'PI',
	'SAPI':'PI',
	'SAPI13':'PI',
	'SAPI14':'PI',
	'SAPI15':'PI',
	'SAPI24':'PI',
	'SAPI25':'PI',
	'SAPI2A':'PI',
	'SAPI2B':'PI',
	'SAPI2C':'PI',
	'SAPI2D':'PI',
	'SAPI33':'PI',
	'SAPI34':'PI',
	'SAPI35':'PI',
	'TMCL1':'CL',
	'TMCL2':'CL',
	'PMCL1':'CL',
	'PMCL2':'CL',
	'PVCL2':'CL',
	'TYCL1':'CL',
	'TYCL2':'CL',
	'TOCL1':'CL',
	'TOCL2':'CL',
	'LOACL1':'CL',
	'LOACL2':'CL',
	'LOCCL1':'CL',
	'LOCCL2':'CL',
	'TLCL1':'CL',
	'TLCL2':'CL',
	'LNCCL1':'CL',
	'LNCCL2':'CL',
	'LNACL1':'CL',
	'LNACL2':'CL',
	'LNDCL1':'CL',
	'LNDCL2':'CL',
	'LNBCL1':'CL',
	'LNBCL2':'CL',
	'SAPA':'PUFA',
	'SAPC':'PUFA',
	'SAPE':'PUFA',
	'SAPG':'PUFA',
	'SAPS':'PUFA',
	'SDPA':'PUFA',
	'SDPC':'PUFA',
	'SDPE':'PUFA',
	'SDPG':'PUFA',
	'SDPS':'PUFA',
	'DAPA':'PUFA',
	'DAPC':'PUFA',
	'DAPE':'PUFA',
	'DAPG':'PUFA',
	'DAPS':'PUFA',
	'PSM':'SM-N',
	'SSM':'SM-N',
	'ASM':'SM-N',
	'BSM':'SM-N',
	'23SM':'SM-N',
	'LSM':'SM-N',
	'OSM':'SM-N',
	'NSM':'SM-N',
	'CER160':'SM-P',
	'CER180':'SM-P',
	'CER181':'SM-P',
	'CER200':'SM-P',
	'CER220':'SM-P',
	'CER240':'SM-P',
	'CER241':'SM-P',
	'QMPE':'Bacterial Lipids',
	'PMPE':'Bacterial Lipids',
	'PMPG':'Bacterial Lipids',
	'PPPE':'Bacterial Lipids',
	'PVPE':'Bacterial Lipids',
	'PVPG':'Bacterial Lipids',
	'APPC':'Bacterial Lipids',
	'IPPC':'Bacterial Lipids',
	'PhPC':'Bacterial Lipids',
	'LAU':'Fatty Acids',
	'MYR':'Fatty Acids',
	'PAL':'Fatty Acids',
	'STE':'Fatty Acids',
	'ARA':'Fatty Acids',
	'BEH':'Fatty Acids',
	'TRI':'Fatty Acids',
	'LIGN':'Fatty Acids',
	'MYRO':'Fatty Acids',
	'PALO':'Fatty Acids',
	'HTA':'Fatty Acids',
	'OLE':'Fatty Acids',
	'LIN':'Fatty Acids',
	'ALIN':'Fatty Acids',
	'SDA':'Fatty Acids',
	'GLA':'Fatty Acids',
	'EICO':'Fatty Acids',
	'EDA':'Fatty Acids',
	'MEA':'Fatty Acids',
	'DGLA':'Fatty Acids',
	'ETE':'Fatty Acids',
	'ETA':'Fatty Acids',
	'EPA':'Fatty Acids',
	'ARAN':'Fatty Acids',
	'HPA':'Fatty Acids',
	'ERU':'Fatty Acids',
	'DDA':'Fatty Acids',
	'ADR':'Fatty Acids',
	'DPT':'Fatty Acids',
	'DPA':'Fatty Acids',
	'DHA':'Fatty Acids',
	'NER':'Fatty Acids',
	'TTA':'Fatty Acids',
	'TPT':'Fatty Acids',
	'TPA':'Fatty Acids',
	'THA':'Fatty Acids',
	'LAUP':'Fatty Acids',
	'MYRP':'Fatty Acids',
	'PALP':'Fatty Acids',
	'STEP':'Fatty Acids',
	'ARAP':'Fatty Acids',
	'BEHP':'Fatty Acids',
	'TRIP':'Fatty Acids',
	'LIGNP':'Fatty Acids',
	'MYROP':'Fatty Acids',
	'PALOP':'Fatty Acids',
	'HTAP':'Fatty Acids',
	'OLEP':'Fatty Acids',
	'LINP':'Fatty Acids',
	'ALINP':'Fatty Acids',
	'SDAP':'Fatty Acids',
	'GLAP':'Fatty Acids',
	'EICOP':'Fatty Acids',
	'EDAP':'Fatty Acids',
	'MEAP':'Fatty Acids',
	'DGLAP':'Fatty Acids',
	'ETEP':'Fatty Acids',
	'ETAP':'Fatty Acids',
	'EPAP':'Fatty Acids',
	'ARANP':'Fatty Acids',
	'HPAP':'Fatty Acids',
	'ERUP':'Fatty Acids',
	'DDAP':'Fatty Acids',
	'ADRP':'Fatty Acids',
	'DPTP':'Fatty Acids',
	'DPAP':'Fatty Acids',
	'DHAP':'Fatty Acids',
	'NERP':'Fatty Acids',
	'TTAP':'Fatty Acids',
	'TPTP':'Fatty Acids',
	'TPAP':'Fatty Acids',
	'THAP':'Fatty Acids',
	'SDS':'Detergents-P',
	'LMPG':'Detergents-P',
	'DHPC':'Detergents-P',
	'FOS10':'Detergents-P',
	'DPC':'Detergents-P',
	'TPC':'Detergents-P',
	'ADDG':'Detergents-2C1',
	'BDDG':'Detergents-2C1',
	'ADG':'Detergents-2C1',
	'BDG':'Detergents-2C1',
	'AOG':'Detergents-2C1',
	'BOG':'Detergents-2C1',
	'ADDM':'Detergents-2O1',
	'BDDM':'Detergents-2O1',
	'ADM':'Detergents-2O1',
	'BDM':'Detergents-2O1',
	'AOM':'Detergents-2O1',
	'BOM':'Detergents-2O1',
	'SB3-12':'Detergents-N',
	'SB3-14':'Detergents-N',
	'LDAO':'Detergents-N'
}

parent_atom = {
 	'Bacterial Lipids':'P',
	'CL':'C3',
	'Fatty Acids':'C1',
	'PA':'P',
	'PC':'P',
	'PE':'P',
	'PG':'P',
	'PI':'P',
	'PS':'P',
	'PUFA':'P',
	'Sterols':'O3',
	'SM-N':'N',
	'SM-NF':'NF',
	'Detergents-P':'P',
	'Detergents-N':'N',
	'Detergents-2C1':'2C1',
	'Detergents-2O1':'2O1'
}
